module.exports = {
  plugins: ['import'],
  rules: {
    'import/default': 'error',
    'import/dynamic-import-chunkname': 'off',
    'import/export': 'error',
    'import/exports-last': 'warn',
    'import/extensions': ['error', 'ignorePackages'],
    'import/first': 'off',
    'import/group-exports': 'warn',
    'import/max-dependencies': 'off',
    'import/named': 'error',
    'import/namespace': ['error', {allowComputed: true}],

    // superseded by 'padding-line-between-statements',
    'import/newline-after-import': 'off',
    'import/no-absolute-path': 'error',
    'import/no-amd': 'off',
    'import/no-anonymous-default-export': 'off',
    'import/no-commonjs': 'off',
    'import/no-cycle': 'warn',
    'import/no-default-export': 'off',
    'import/no-deprecated': 'warn',
    'import/no-duplicates': ['warn', {considerQueryString: true}],
    'import/no-dynamic-require': 'off',

    // superseded by 'node/no-extraneous-import' and 'node/no-extraneous-require'
    'import/no-extraneous-dependencies': 'off',
    'import/no-import-module-exports': 'off',
    'import/no-internal-modules': 'off',
    'import/no-mutable-exports': 'off',
    'import/no-named-as-default': 'off',
    'import/no-named-as-default-member': 'off',
    'import/no-named-default': 'warn',
    'import/no-named-export': 'off',
    'import/no-namespace': 'off',
    'import/no-nodejs-modules': 'off',
    'import/no-relative-packages': 'off',
    'import/no-relative-parent-imports': 'off',
    'import/no-restricted-paths': 'off',
    'import/no-self-import': 'warn',
    'import/no-unassigned-import': 'off',

    // superseded by 'node/no-missing-import' and 'node/no-missing-require'
    'import/no-unresolved': 'off',
    'import/no-unused-modules': 'off',
    'import/no-useless-path-segments': 'warn',
    'import/no-webpack-loader-syntax': 'error',
    'import/order': 'warn',
    'import/prefer-default-export': 'warn',
    'import/unambiguous': 'off',
  },
};
