module.exports = {
  rules: {
    'accessor-pairs': 'warn',
    'array-bracket-newline': 'warn',
    'array-bracket-spacing': 'warn',
    'array-callback-return': 'warn',
    'array-element-newline': ['warn', 'consistent'],
    'arrow-body-style': 'warn',
    'arrow-parens': 'warn',
    'arrow-spacing': 'warn',

    // not allowing `var` declarations
    'block-scoped-var': 'off',

    // not allowing opening and closing braces on the same line
    'block-spacing': 'off',
    'brace-style': ['warn', 'stroustrup'],
    camelcase: 'warn',
    'capitalized-comments': ['warn', 'never'],
    'class-methods-use-this': 'warn',
    'comma-dangle': ['warn', 'always-multiline'],
    'comma-spacing': 'warn',
    'comma-style': 'warn',
    complexity: 'off',
    'computed-property-spacing': 'warn',
    'consistent-return': 'warn',
    'consistent-this': 'warn',
    'constructor-super': 'error',
    curly: 'warn',
    'default-case': 'warn',
    'default-case-last': 'off',
    'default-param-last': 'off',
    'dot-location': ['warn', 'property'],
    'dot-notation': 'warn',
    'eol-last': 'warn',
    eqeqeq: 'warn',
    'for-direction': 'warn',
    'func-call-spacing': 'warn',
    'func-name-matching': 'warn',
    'func-names': 'warn',
    'func-style': 'warn',
    'function-call-argument-newline': ['warn', 'consistent'],
    'function-paren-newline': 'warn',
    'generator-star-spacing': ['warn', 'after'],
    'getter-return': 'warn',
    'grouped-accessor-pairs': ['warn', 'setBeforeGet'],

    // not allowing `for...in` loops
    'guard-for-in': 'off',
    'implicit-arrow-linebreak': 'warn',
    indent: ['warn', 2, {SwitchCase: 1, offsetTernaryExpressions: true}],
    'init-declarations': 'off',
    'jsx-quotes': 'warn',
    'key-spacing': 'warn',
    'keyword-spacing': 'warn',
    'line-comment-position': 'warn',
    'linebreak-style': 'warn',
    'lines-around-comment': [
      'warn',
      {
        beforeBlockComment: true,
        afterBlockComment: true,
        beforeLineComment: true,
        afterLineComment: false,
        allowBlockStart: true,
        allowBlockEnd: true,
        allowClassStart: true,
        allowClassEnd: true,
        allowObjectStart: true,
        allowObjectEnd: true,
        allowArrayStart: true,
        allowArrayEnd: true,
      },
    ],
    'lines-between-class-members': [
      'warn',
      'always',
      {exceptAfterSingleLine: true},
    ],
    'max-classes-per-file': 'off',
    'max-depth': 'off',
    'max-len': 'warn',
    'max-lines': 'off',
    'max-lines-per-function': 'off',
    'max-nested-callbacks': 'off',
    'max-params': 'off',
    'max-statements': 'off',
    'max-statements-per-line': 'off',
    'multiline-comment-style': 'off',
    'multiline-ternary': ['warn', 'always-multiline'],
    'new-cap': 'warn',
    'new-parens': 'warn',
    'newline-per-chained-call': ['warn', {ignoreChainWithDepth: 1}],
    'no-alert': 'off',
    'no-array-constructor': 'warn',
    'no-async-promise-executor': 'warn',
    'no-await-in-loop': 'off',
    'no-bitwise': 'off',
    'no-caller': 'off',
    'no-case-declarations': 'warn',
    'no-class-assign': 'warn',
    'no-compare-neg-zero': 'warn',
    'no-cond-assign': ['warn', 'always'],
    'no-confusing-arrow': 'off',
    'no-console': 'off',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'warn',
    'no-constant-condition': 'warn',
    'no-constructor-return': 'warn',
    'no-continue': 'off',
    'no-control-regex': 'warn',
    'no-debugger': 'off',
    'no-delete-var': 'warn',
    'no-div-regex': 'off',
    'no-dupe-args': 'warn',
    'no-dupe-class-members': 'warn',
    'no-dupe-else-if': 'warn',
    'no-dupe-keys': 'warn',
    'no-duplicate-case': 'warn',
    'no-duplicate-imports': ['warn', {includeExports: true}],
    'no-else-return': ['warn', {allowElseIf: false}],
    'no-empty': 'warn',
    'no-empty-character-class': 'warn',
    'no-empty-function': 'warn',
    'no-empty-pattern': 'warn',

    // not allowing non-type-checking equality operators
    'no-eq-null': 'off',
    'no-eval': 'off',
    'no-ex-assign': 'warn',
    'no-extend-native': 'warn',
    'no-extra-bind': 'warn',
    'no-extra-boolean-cast': ['warn', {enforceForLogicalOperands: true}],
    'no-extra-label': 'warn',
    'no-extra-parens': 'off',
    'no-extra-semi': 'warn',
    'no-fallthrough': 'warn',
    'no-floating-decimal': 'warn',

    // not allowing `function` declarations
    'no-func-assign': 'off',
    'no-global-assign': 'warn',
    'no-implicit-coercion': 'warn',

    // not allowing `var` or `function` declarations, assignment to undeclared
    // variables, redeclaration of global variables, or assignment to read-only
    // global variables
    'no-implicit-globals': 'off',
    'no-implied-eval': 'off',
    'no-import-assign': 'warn',

    // superseded by line-comment-position
    'no-inline-comments': 'off',

    // not allowing `var` or `function` declarations
    'no-inner-declarations': 'off',
    'no-invalid-regexp': 'error',
    'no-invalid-this': 'warn',
    'no-irregular-whitespace': ['warn', {skipStrings: true}],
    'no-iterator': 'warn',
    'no-label-var': 'warn',
    'no-labels': 'off',
    'no-lone-blocks': 'warn',
    'no-lonely-if': 'warn',
    'no-loop-func': 'warn',
    'no-loss-of-precision': 'warn',
    'no-magic-numbers': 'off',
    'no-misleading-character-class': 'warn',
    'no-mixed-operators': 'warn',

    // not allowing tabs
    'no-mixed-spaces-and-tabs': 'off',
    'no-multi-assign': 'warn',
    'no-multi-spaces': 'warn',
    'no-multi-str': 'warn',
    'no-multiple-empty-lines': ['warn', {max: 1}],
    'no-negated-condition': 'off',
    'no-nested-ternary': 'off',
    'no-new': 'off',
    'no-new-func': 'warn',
    'no-new-object': 'warn',
    'no-new-symbol': 'error',
    'no-new-wrappers': 'warn',
    'no-nonoctal-decimal-escape': 'warn',
    'no-obj-calls': 'error',
    'no-octal': 'warn',
    'no-octal-escape': 'warn',
    'no-param-reassign': ['warn', {props: true}],
    'no-plusplus': 'off',
    'no-promise-executor-return': 'warn',
    'no-proto': 'warn',
    'no-prototype-builtins': 'warn',

    // not allowing `var` declarations
    'no-redeclare': 'off',
    'no-regex-spaces': 'warn',
    'no-restricted-exports': 'off',
    'no-restricted-globals': [
      'error',
      {
        name: 'isFinite',
        message: 'Use Number.isFinite() instead',
      },
      {
        name: 'isNaN',
        message: 'Use Number.isNaN() instead',
      },
      {
        name: 'parseFloat',
        message: 'Use Number.parseFloat() instead',
      },
      {
        name: 'parseInt',
        message: 'Use Number.parseInt() instead',
      },
    ],
    'no-restricted-imports': 'off',
    'no-restricted-modules': 'off',
    'no-restricted-properties': 'off',
    'no-restricted-syntax': [
      'error',
      {
        selector: 'ForInStatement',
        message: 'Use for...of with Object.keys(), .values(), and .entries()'
          + ' instead',
      },
    ],
    'no-return-assign': ['warn', 'always'],
    'no-return-await': 'off',
    'no-script-url': 'off',
    'no-self-assign': 'warn',
    'no-self-compare': 'warn',
    'no-sequences': 'off',
    'no-setter-return': 'warn',
    'no-shadow': ['warn', {builtinGlobals: true}],

    // superseded by no-shadow
    'no-shadow-restricted-names': 'off',
    'no-sparse-arrays': 'off',
    'no-tabs': 'warn',
    'no-template-curly-in-string': 'off',
    'no-ternary': 'off',
    'no-this-before-super': 'error',
    'no-throw-literal': 'warn',
    'no-trailing-spaces': 'warn',
    'no-undef': ['error', {typeof: true}],
    'no-undef-init': 'warn',
    'no-undefined': 'warn',
    'no-underscore-dangle': 'off',
    'no-unexpected-multiline': 'warn',
    'no-unmodified-loop-condition': 'warn',
    'no-unneeded-ternary': ['warn', {defaultAssignment: false}],
    'no-unreachable': 'warn',
    'no-unreachable-loop': 'warn',
    'no-unsafe-finally': 'warn',
    'no-unsafe-negation': ['warn', {enforceForOrderingRelations: true}],
    'no-unsafe-optional-chaining': [
      'warn',
      {disallowArithmeticOperators: true},
    ],
    'no-unused-expressions': 'warn',
    'no-unused-labels': 'warn',
    'no-unused-private-class-members': 'warn',
    'no-unused-vars': ['warn', {args: 'all', ignoreRestSiblings: true}],
    'no-use-before-define': 'error',
    'no-useless-backreference': 'warn',
    'no-useless-call': 'warn',
    'no-useless-catch': 'warn',
    'no-useless-computed-key': ['warn', {enforceForClassMembers: true}],
    'no-useless-concat': 'warn',
    'no-useless-constructor': 'warn',
    'no-useless-escape': 'warn',
    'no-useless-rename': 'warn',
    'no-useless-return': 'warn',
    'no-var': 'warn',
    'no-void': 'off',
    'no-warning-comments': 'off',
    'no-whitespace-before-property': 'warn',
    'no-with': 'warn',

    // not allowing non-block statements
    'nonblock-statement-body-position': 'off',
    'object-curly-newline': ['warn', {multiline: true}],
    'object-curly-spacing': 'warn',
    'object-property-newline': ['warn', {allowAllPropertiesOnSameLine: true}],
    'object-shorthand': ['warn', 'always', {avoidExplicitReturnArrows: true}],
    'one-var': ['warn', 'never'],

    // not allowing multiple variable declarations in a single `var`, `let`, or
    // `const` statement
    'one-var-declaration-per-line': 'off',
    'operator-assignment': 'warn',
    'operator-linebreak': ['warn', 'before'],
    'padded-blocks': ['warn', 'never'],
    'padding-line-between-statements': [
      'warn',
      {
        prev: '*',
        next: ['cjs-export', 'cjs-import', 'directive', 'const', 'let'],
        blankLine: 'always',
      },
      {
        prev: ['cjs-export', 'cjs-import', 'directive', 'const', 'let'],
        next: '*',
        blankLine: 'always',
      },
      {
        prev: 'cjs-import',
        next: 'cjs-import',
        blankLine: 'never',
      },
      {
        prev: 'cjs-export',
        next: 'cjs-export',
        blankLine: 'never',
      },
      {
        prev: ['const', 'let'],
        next: ['const', 'let'],
        blankLine: 'never',
      },
      {
        prev: 'directive',
        next: 'directive',
        blankLine: 'never',
      },
      {
        prev: 'export',
        next: 'export',
        blankLine: 'never',
      },
      {
        prev: 'import',
        next: 'import',
        blankLine: 'never',
      },
      {
        prev: '*',
        next: [
          'multiline-block-like',
          'multiline-const',
          'multiline-expression',
          'multiline-let',
        ],
        blankLine: 'always',
      },
      {
        prev: [
          'multiline-block-like',
          'multiline-const',
          'multiline-expression',
          'multiline-let',
        ],
        next: '*',
        blankLine: 'always',
      },
    ],
    'prefer-arrow-callback': ['warn', {allowUnboundThis: false}],
    'prefer-const': 'warn',
    'prefer-destructuring': [
      'warn',
      {array: true, object: true},
      {enforceForRenamedProperties: true},
    ],
    'prefer-exponentiation-operator': 'warn',
    'prefer-named-capture-group': 'off',
    'prefer-numeric-literals': 'warn',
    'prefer-object-has-own': 'warn',
    'prefer-object-spread': 'warn',
    'prefer-promise-reject-errors': 'warn',
    'prefer-regex-literals': ['warn', {disallowRedundantWrapping: true}],
    'prefer-rest-params': 'warn',
    'prefer-spread': 'warn',
    'prefer-template': 'warn',
    'quote-props': ['warn', 'as-needed'],
    quotes: ['warn', 'single'],
    radix: 'warn',
    'require-atomic-updates': 'warn',
    'require-await': 'warn',
    'require-unicode-regexp': 'warn',
    'require-yield': 'warn',
    'rest-spread-spacing': 'warn',
    semi: ['warn', 'always', {omitLastInOneLineBlock: true}],
    'semi-spacing': ['warn', {before: false, after: true}],
    'semi-style': 'warn',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'sort-vars': 'off',
    'space-before-blocks': 'warn',
    'space-before-function-paren': [
      'warn',
      {anonymous: 'never', named: 'never', asyncArrow: 'always'},
    ],
    'space-in-parens': 'warn',
    'space-infix-ops': 'warn',
    'space-unary-ops': 'warn',
    'spaced-comment': 'warn',
    strict: 'off',
    'switch-colon-spacing': 'warn',
    'symbol-description': 'off',
    'template-curly-spacing': 'warn',
    'template-tag-spacing': 'warn',
    'unicode-bom': 'warn',
    'use-isnan': ['warn', {enforceForIndexOf: true}],
    'valid-typeof': ['warn', {requireStringLiterals: true}],

    // not allowing `var` declarations
    'vars-on-top': 'off',
    'wrap-iife': ['warn', 'inside'],
    'wrap-regex': 'off',
    'yield-star-spacing': ['warn', 'after'],
    yoda: 'warn',
  },
};
